### ISSUE TITLE
Strips path fragments

### ISSUE THREAD

**Issue by karolisgrinkevicius** [jonschlinkert/normalize-path#11]
Hi there. I have the following use case:
```js
import normalize from 'path-normalize';

const normalizeUrl = (url: string) => {
  const urlObject = URL(url);
  urlObject.set('pathname', normalize(urlObject.pathname));
  return urlObject.toString();
};

expect(normalizeUrl('https://example.com/badpath//or/.././subpath//data.json')).toEqual(
  'https://example.com/badpath/or/subpath/data.json',
);
```
In version `2.1.1` this was working as expected and assertion was always successful. Since version `3` it's failing with the following output:

```sh
Expected value to equal:
  "https://example.com/badpath/or/subpath/data.json"
Received:
  "https://example.com/badpath/subpath/data.json"
```

Is this expected? If so you should have mentioned it in the breaking changes list.

**Comment by doowb** [comment]
It looks like the double slashes are removed, but the `../.` part is evaluated and the `or` segment is removed. Since `normalize-path` doesn't do anything with `../.`, I think the `URL` function is doing that and causing your test to fail.

Edit: I didn't see the title update until after I posted my comment.

**Comment by jonschlinkert** [comment]
Hi @karolisgrinkevicius, here is what this library returns for your path:

```js
const path = require('normalize-path');
console.log(path(('https://example.com/badpath//or/.././subpath//data.json')));
// https:/example.com/badpath/or/.././subpath/data.json
```

The issue you described, as pointed out by @doowb seems to not be related to this library.

**Comment by karolisgrinkevicius** [comment]
@doowb @jonschlinkert thanks for clarifying this. The weird thing is that the unit test didn't fail until I upgraded version of `normalize-path` to the latest one `2.1.1`.
