### ISSUE TITLE
Normalize path with ".." elements

### ISSUE THREAD

**Issue by niondir** [jonschlinkert/normalize-path#12]
I like to normalize a path like `/foo/bar/..` to `/foo/`

This seems not to be supported. Would it be a desired feature or do you know any other library to help me with this?

Actually https://golang.org/pkg/path/#Clean is doing exactly what I need in JS.

**Comment by doowb** [comment]
This package is to:

> Normalize slashes in a file path to be posix/unix-like forward slashes. Also condenses repeat slashes to a single slash and removes and trailing slashes, unless disabled.

You can use the built in [path.normalize](https://nodejs.org/api/path.html#path_path_normalize_path) first to remove the `..` pieces:

```js
const path = require('path');
const normalize = require('normalize-path');
console.log(normalize(path.normalize('/foo/bar/..'));
```

**Comment by niondir** [comment]
Is there any path.normalize implementation for the browser?
