### ISSUE TITLE
Use `remove-trailing-separator` module as dependency?

### ISSUE THREAD

**Issue by phated** [jonschlinkert/normalize-path#3]
Was thinking it might be better to use that module as a dependency instead of the regexp.

Ref https://github.com/darsain/remove-trailing-separator

**Comment by jonschlinkert** [comment]
yeah I think that's a good idea since remove-trailing-separator supports windows paths too

**Comment by phated** [comment]
I might have a chance today.  I'm working on a couple other things at the moment and stumbled here.

**Comment by phated** [comment]
@jonschlinkert that module removes a series of trailing separators (e.g. `/path/to/something///` becomes `/path/to/something`).  Is that okay?

**Comment by jonschlinkert** [comment]
yeah, I think that would be fine. thx
