### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by ZeeCoder** [jonschlinkert/normalize-path#7]
I've just realised I'm behind a major version with this library, but I'm not entirely sure if there was an actual breaking change from my point of view:
https://github.com/jonschlinkert/normalize-path/compare/2.1.1...3.0.0

Could you consider writing a changelog?
I can help out if you need it. 👍

**Comment by jonschlinkert** [comment]
I don't recall there being any breaking changes, but a PR for a changelog would be great!
