### ISSUE TITLE
Missing remove-trailing-separator dependency

### ISSUE THREAD

**Issue by aalibasic** [jonschlinkert/normalize-path#8]
When npm installing version 2.1.1 of this lib, npm did not install the required peer: 'remove-trailing-separator'

**Comment by doowb** [comment]
`remove-trailing-separator` is listed in the `package.json` `dependencies` list, so this is an issue with npm. Usually deleting the `node_modules` and `package-lock.json`, then clearing the npm cache and installing again will fix the issue. If not then something might be wrong with the npm service.

These are the steps I take:

```shell
$ rm package-lock.json
$ rm -fr node_modules
$ npm cache clear --force
$ npm install
```
